### ISSUE TITLE
nothing happening with test command

### ISSUE THREAD

**Issue by aTylerRice** [bcoe/thumbd#103]
I setup a thumbd server on heroku. I've run this command ```heroku run thumbd thumbnail --remote_image=http://i.livescience.com/images/i/000/054/836/i02/beach-sea-130716.jpg --descriptions=http://api.myjson.com/bins/1qooo --app imdown-thumb-test```

I get this in the logs 2015-09-22T18:04:18.603023+00:00 heroku[run.8256]: Awaiting client
2015-09-22T18:04:18.647622+00:00 heroku[run.8256]: Starting process with command `node bin/thumbd server thumbnail --remote_image=http://i.livescience.com/images/i/000/054/836/i02/beach-sea-130716.jpg --descriptions=http://api.myjson.com/bins/1qooo`

and then a bunch of these 2015-09-22T18:04:18.691401+00:00 app[thumbd.1]: wait for message on imdown_thumb_test

I don't get anything in my bucket.

**Comment by wiredmax** [comment]
Yon don't specify your bucket, SQS queue and AWS credentials.

I dont see any: `--aws_key=<key> --aws_secret=<secret> --sqs_queue=<sqs queue name> [--aws_region=<region>]` in the command you provided.
