### ISSUE TITLE
Feature Request: Maintain Custom Headers (User Metadata)

### ISSUE THREAD

**Issue by aggied** [bcoe/thumbd#82]
Will get to this tomorrow, but before I start looking at how to best make sure the images maintain their custom headers I wanted to make sure this isn't yet a feature?

[This line in saver.js](https://github.com/bcoe/thumbd/blob/master/lib/saver.js#L28) leads me to believe we are dropping all the custom headers that came with the image? 

Assuming this is a legitimate feature request, I'm assuming the place to start is `grabber.js`? Is that where the headers are being dropped?

**Comment by bcoe** [comment]
@aggied +1 for this feature, do you have a specific use-case in mind?

**Comment by aggied** [comment]
Nothing in production, but there are a few side projects I'm working on that would benefit from using thumbd if the metadata was persistent. I've got a few hours tonight to explore the feature.

**Comment by aggied** [comment]
Committed to my fork an initial attempt at keeping the metadata. I've tested this on a file without any custom headers, with one custom header, and with multiple. All seems to be working great, but I imagine you'll find some improvements. 

I did add two options to the config, but haven't yet tested them out beyond the defaults. 

[Here's the pull request](https://github.com/bcoe/thumbd/pull/81)

**Comment by bcoe** [comment]
Addressed here: https://github.com/bcoe/thumbd/pull/84
