### ISSUE TITLE
Node 0.12 / io.js support

### ISSUE THREAD

**Issue by rubenstolk** [bcoe/thumbd#90]
Currently when running thumbd on for example Heroku as a worker, it runs absolutely smoothly on Node 0.10, but when using 0.12 or io.js, memory consumption grows with each `process.nextTick`. I've spend a few hours today but couldn't really figure out the reason yet... Opened a PR to make the code a bit cleaner though...

Does anyone have a clue?

**Comment by bcoe** [comment]
@rubenstolk just received an email from Amazon:

```Dear Amazon Web Services Customer,

Our logs indicate that your account has used or is using a version of the AWS SDK for JavaScript that is affected by a memory usage bug when downloading objects from Amazon S3. The affected versions are 2.1.13, 2.1.14, and 2.1.15.

The latest 2.1.16 version of the SDK includes the related fix, and it is critical that you upgrade to the latest version to avoid being affected by it.

The latest version can be found on both npm and GitHub.```

want to check whether upgrading to 2.1.16 solves your issues?

**Comment by rubenstolk** [comment]
I'll definitely try although I've seen the issue arise when the service is just polling, no jobs hence no downloads from S3. On a short holiday now but will give it a shot next week.

--
BR, Ruben Stolk
+919561050034  |  +31646118037




On Fri, Mar 6, 2015 at 3:39 PM -0800, "Benjamin E. Coe" <notifications@github.com> wrote:












@rubenstolk just received an email from Amazon:



```Dear Amazon Web Services Customer,



Our logs indicate that your account has used or is using a version of the AWS SDK for JavaScript that is affected by a memory usage bug when downloading objects from Amazon S3. The affected versions are 2.1.13, 2.1.14, and 2.1.15.



The latest 2.1.16 version of the SDK includes the related fix, and it is critical that you upgrade to the latest version to avoid being affected by it.



The latest version can be found on both npm and GitHub.```



want to check whether upgrading to 2.1.16 solves your issues?



—
Reply to this email directly or view it on GitHub.

**Comment by rubenstolk** [comment]
It indeed seems to be solved by upgrading the `aws-sdk`, see my PR
